name: Deployment
#deploy 전체는 작성해올것

on:
  push:
    branches:
      - main

jobs:
  backtest:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: set env
        working-directory: ./mock-test
        run: |
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" > .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MESSAGE=${{ secrets.MESSAGE }}" >> .env

      - name: Install dependencies of backend
        working-directory: ./mock-test
        run: npm i

      - name: Run Test of backend
        working-directory: ./mock-test
        run: npm test

  fronttest:
    runs-on: ubuntu-latest
    needs: backtest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies of backend
        working-directory: ./todo_list
        run: npm i

      - name: Run Test of backend
        working-directory: ./todo_list
        run: npm test
